// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/printfromai/core/web/templates/components"

// Base is the master shell for PrintFromAI.
func Base(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" class=\"dark\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/layout/base.templ`, Line: 12, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><script src=\"https://unpkg.com/@tailwindcss/browser@4\"></script><script src=\"https://unpkg.com/htmx.org@1.9.10\"></script><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin=\"anonymous\"><link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap\" rel=\"stylesheet\"><script>\r\n\t\t\t\tif (localStorage.getItem('theme') === 'light') {\r\n\t\t\t\t\tdocument.documentElement.classList.remove('dark');\r\n\t\t\t\t} else {\r\n\t\t\t\t\tdocument.documentElement.classList.add('dark');\r\n\t\t\t\t\tlocalStorage.setItem('theme', 'dark');\r\n\t\t\t\t}\r\n\t\t\t</script><style>\r\n\t\t\t\tbody { font-family: 'Inter', sans-serif; }\r\n\t\t\t\thtml { transition: background-color 0.3s ease, color 0.3s ease; }\r\n\t\t\t\t::-webkit-scrollbar { width: 6px; }\r\n\t\t\t\t::-webkit-scrollbar-track { background: transparent; }\r\n\t\t\t\t::-webkit-scrollbar-thumb { background-color: #3f3f46; border-radius: 10px; }\r\n\t\t\t</style></head><body class=\"bg-gray-50 text-gray-800 dark:bg-[#0F0F0F] dark:text-gray-200 antialiased min-h-screen flex w-full overflow-hidden selection:bg-indigo-500 selection:text-white\"><!-- Call the Sidebar component here -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Sidebar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<main id=\"main-content\" class=\"flex-1 flex flex-col h-screen overflow-y-auto relative w-full\" hx-history-elt>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</main><script>\r\n\t\t\t\tfunction toggleTheme() {\r\n\t\t\t\t\tconst html = document.documentElement;\r\n\t\t\t\t\tif (html.classList.contains('dark')) {\r\n\t\t\t\t\t\thtml.classList.remove('dark');\r\n\t\t\t\t\t\tlocalStorage.setItem('theme', 'light');\r\n\t\t\t\t\t} else {\r\n\t\t\t\t\t\thtml.classList.add('dark');\r\n\t\t\t\t\t\tlocalStorage.setItem('theme', 'dark');\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
